### ISSUE TITLE
check correctness of test cases

### ISSUE THREAD

**Issue by kamilsk** [octolab/Cleaner#15]
configuration for packages: https://github.com/octolab/Cleaner/blob/master/tests/fixtures/packages.yml

test cases: https://github.com/octolab/Cleaner/tree/master/tests/fixtures/testcases/matcher/weight

example:
project configuration https://github.com/octolab/Cleaner/blob/master/tests/fixtures/testcases/matcher/weight/mixed/setup.yml#L5-L11

categories for removing https://github.com/octolab/Cleaner/blob/master/tests/fixtures/testcases/matcher/weight/mixed/expected.yml#L1-L5

**Comment by kamilsk** [comment]
@mlocati could you help with the issue?

**Comment by mlocati** [comment]
> @mlocati could you help with the issue?

Sorry but I don't understand what would you like me to do... Should I manually check if the `expected.yml` files are good for their corresponding `setup.yml` files?

**Comment by kamilsk** [comment]
That all test cases have correct behavior. package.yml (input) - setup.yml (rules) - expected.yml (output)

**Comment by mlocati** [comment]
Yes, everything is fine. Good work!

**Comment by kamilsk** [comment]
ok, thanks
