### ISSUE TITLE
implement FakeCleaner

### ISSUE THREAD

**Issue by kamilsk** [octolab/Cleaner#20]

**Comment by kamilsk** [comment]
@mlocati, I completed FakeCleaner, its output looks like this http://screencast.com/t/3BSrxD0PWli

configuration presented here: https://github.com/octolab/Cleaner/tree/master/tests/integration/project (important this https://github.com/octolab/Cleaner/blob/master/tests/integration/project/composer.json#L27)

available configuration for plugin presented here https://github.com/octolab/Cleaner/blob/master/src/Plugin.php#L58-L64

If you want you can try debug mode and see what happens with your packages

**Comment by kamilsk** [comment]
@mlocati, clean renamed to clear: https://github.com/octolab/Cleaner/commit/ef33d707f1a7220d4dd5abfbc8af7a97c5fa383c

FYI

**Comment by mlocati** [comment]
Everything is working really fine! Really good work

**Comment by kamilsk** [comment]
glad to hear it! 👍 I hope this will be useful

**Comment by mlocati** [comment]
Me too :wink: I'll start opening pull requests :smile:

**Comment by mlocati** [comment]
I noticed a problem with the strict types declaration: https://github.com/composer/composer/pull/5393 should fix this
