### ISSUE TITLE
PHP 7.2 & 7.3 error

### ISSUE THREAD

**Issue by marcing** [octolab/Cleaner#57]
```
Deprecation Notice: assert(): Calling assert() with a string argument is deprecated in vendor/octolab/cleaner/src/Util/GlobFinder.php:40
```

**Comment by kamilsk** [comment]
fixed: https://travis-ci.org/octolab/cleaner/builds/496657848, https://scrutinizer-ci.com/g/octolab/cleaner/inspections/9ffb491d-a35a-4a07-aba3-dd3fa22d2e3e

thanks @marcing

**Comment by marcing** [comment]
Thank you for a quick fix!

Marcin
